services:
  llastro:
    build:
      context: .
    ports:
      - "4321:4321"
    environment:
      STORAGE_ROOT: /app/storage
      ENABLE_APPJS: "false"
    volumes:
      - ./storage:/app/storage:Z
